### ISSUE TITLE
Blank Web App

### ISSUE THREAD

**Issue by rena-ganba** [roscisz/TensorHive#217]
Hi,

I have already successfully install from source and set the ssh as well as user. On the terminal it said that the web app was up on 0.0.0.0:5000, but after I opened it, it is just a blank page. What may cause this?

**Comment by roscisz** [comment]
Hi @rena-gamba,
Thank you for trying TH and even more for issuing this bug report. Apparently we didn't upload the newest version of the web app with the r0.3 release. 

Fixed in 69212d89483e15b69c7d5b72c112bcb718bb8b6f.

Pulling from master (and maybe clearing browsing history) should solve the problem. If you find the time, please let us know if this helped.
