### ISSUE TITLE
Add groups to user overview

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#251]

**Comment by martyole** [comment]
Current changes include a code refactor – extracting UsersInfo component from UsersOverview and creating GroupsInfo component.

Group view was added to UsersOverview panel. This allows creating groups (adding existing users, adding resource permissions for groups), editing and deleting groups. Users and groups count was added above data tables.
Current changes don’t use API functions yet, they work on mocked data.

TODO:
-use new API functions instead of mocks
-allow managing resource permissions – creating, deleting and editing
-add assigning permissions for single users (when creating/editing users)

https://github.com/martyole/TensorHive/commit/da7d3b6f8024f81ea6e8553a6fd0559f8c076872

![Zrzut ekranu z 2020-09-18 18-52-53](https://user-images.githubusercontent.com/48392465/93626331-96bbbd80-f9e3-11ea-8ede-f4d9e0352af3.png)
![Zrzut ekranu z 2020-09-18 18-53-31](https://user-images.githubusercontent.com/48392465/93626337-97545400-f9e3-11ea-9592-dc9b4806633d.png)
![Zrzut ekranu z 2020-09-18 18-54-12](https://user-images.githubusercontent.com/48392465/93626340-97ecea80-f9e3-11ea-8fbb-26ceada9eed1.png)
![Zrzut ekranu z 2020-09-18 18-58-15](https://user-images.githubusercontent.com/48392465/93626341-97ecea80-f9e3-11ea-8238-d48b8346dc44.png)

**Comment by roscisz** [comment]
fixed in #307
