### ISSUE TITLE
Does TensorHive support automatic scheduling/assignment to an available node?

### ISSUE THREAD

**Issue by infokiller** [roscisz/TensorHive#292]
Hi!

I just started playing with TensorHive and I'm trying to understand if it fits my needs. 
My use case is that I have multiple nodes (servers with GPUs) and multiple users that want to run ML tasks on these GPUs, with the goal of maximizing utilization, and supporting scheduling priority and fairness.

When I create a new task in the web UI, it requires me to input the hostname. Does that mean I can't submit a task, and have TensorHive automatically select the best node (based on available resources)?

In addition, does TensorHive include any support for packaging code and data, for example by using a Docker container?

Thanks!

**Comment by micmarty** [comment]
0. Thanks for checking out our project and sorry for not responding that long (vacations). TensorHive puts huge emphasis on scheduling resources for particular time range (hence calendar). We didn't want to make another Slurm or Kubernetes, but something with different philosophy that makes sense at our university.
1. Currently there is no support for automatic hardware selection, but it is planned to add in the nearest future (other users have similar need)
2. TensorHive in current shape is completely agnostic when it comes to code, it just cares about running a shell command, that's all. That decision was made in order to not enforce any specific tech stack. So according to your question, you can use guild.ai, neptune.ai, DVC, whatever, it's up to you. 

If you have any suggestions in this topic, please let us know. We'd love to get some feedback, discuss your use-case.

**Comment by infokiller** [comment]
Thanks for the detailed response!
I'm still figuring out what workflow will work best for my team, but automatic scheduling is probably a must (along with a workflow for packaging code and data to be able to run on any machine).
Once TensorHive supports scheduling (which also requires for jobs to specify hardware requirements), I guess I will be able to use it by running something like `docker run` and (and push the image to a private registry prior to that).

**Comment by roscisz** [comment]
@infokiller Thanks for your input! Sorry for late answer, as @micmarty mentioned, I was travelling.

The primary concept behind TH is granting exclusive, reserved in advance access to selected GPUs to the user, which is especially useful for interactive work. However, we are currently planning a [task queue](#267), which will allow to schedule tasks when there are no reservations. Indeed, simple scheduling will be required to use such a queue. Would you consider suggesting reasonable practical use-cases in the [appropriate issue](#267)?

Regarding code and data packaging, for the sake of simplicity and usability, we decided that TH will abstract from it and assume that the command specified for the task can take care of it. So exactly, using something like `docker run` under the hood was our intention. If experiences with this approach will suggest some potential improvements in TH, we could add some kind of helper templates (like the templates for distributed TensorFlow and PyTorch).

**Comment by infokiller** [comment]
@roscisz no worries and thanks for the update. I agree with the decision of being agnostic to any runtime and using a simple command, which can run docker or whatever.
Re your primary use case of reserving resources for interactive work, is there a particular reason why you don't support specifying hardware requirements, and then automatically assigning an appropriate machine?

**Comment by roscisz** [comment]
@infokiller regarding the interactive work use case - it was suggested by our first target users, namely three research teams (a team within a private company, research team at my university and a student interest group). These were relatively small work groups focused on deep learning with access to a few shared servers with GPUs. Some of the users were mathematicians, statisticians and programmers with limited experience with DevOps and queuing systems. There was no admin to take care of a queuing system such as SLURM or Kubernetes. Often there was no network filesystem for data storage. As the admin of some of the servers I didn't want Docker, because the processes would be executed as root.

Typically, the user was working on a project utilizing a specific server or two, had everything set up in the base OS (files, data, virtualenv) and the problem was to synchronize the growing teams, hence the calendar. Introducing a simple tool allowed users to communicate easier about the server utilization, but also made them plan the reservations more thoughtfully (everyone could see if I reserved the GPU for one week, and the avg utilization was 1% - shame!).

This helped a lot, the calendars became more and more crowded, but we noticed the possibility to utilize the hardware even better by queuing tasks with priority lower than the interactive work and running them when there are no reservations, hence issue #267. I plan to implement a simple version of the queue, as soon as we finish [access control](https://github.com/roscisz/TensorHive/milestone/7) and [task execution improvement](https://github.com/roscisz/TensorHive/milestone/8) milestones.
