### ISSUE TITLE
Can't register unix user account in Tensorhive version 0.3.6

### ISSUE THREAD

**Issue by William-Le88** [roscisz/TensorHive#325]
Running Tensorhive, the Tensorhive web Apps require user login which I created unix username earlier in "tensorhive init" command. However, I could not login into the webpage and it thrown error  
{"detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.", "status": 500, "title":"Internal Server error", "type": "about: blank"}

I tried to registered other unix username by clicking in register button: It shown me another error of: "Unprivileged".

Please find my environment as below:
OS distribution, version: Ubuntu 18.04 LTS
Tensorhive: version 0.3.6
GPU model:

### Your environment
List relevant info:
* OS distribution, version
* TensorHive and API version
* Versions of installed dependencies
* Essential hardware specs (GPU model)

### Steps to reproduce
Tell us how to reproduce this issue from the ground up.

```
![image](https://user-images.githubusercontent.com/78297811/107117969-e7f81b00-68b8-11eb-89de-dd8647a10df6.png)
![image](https://user-images.githubusercontent.com/78297811/107117972-ededfc00-68b8-11eb-91c3-7db0f94238c1.png)

Thank you!
Best Regards,
William Le

**Comment by roscisz** [comment]
Hi William!

Thank you for reaching out.

I see two separate issues here:
1. Logging in as the user created at the `tensorhive init` stage should work out of the box. The Internal Server Error 500 indeed indicates that something's wrong, but details are missing. Do you see any errors in TH log (in the console where you execute `tensorhive`) upon login trial?

2. Another user can indeed register themselves without the help of the admin. To do this, they need an OS account on the first server that is monitored by TH and follow the instructions given in the registration form: perform authentication by copying the TH public key to .ssh/authorized_keys:

![image](https://user-images.githubusercontent.com/766386/107208762-509edf00-6a02-11eb-9a46-3636dbfd2b30.png)

**Comment by William-Le88** [comment]
Dear Roscisz,

Thank you so much for kind support.
Please let me add further input based on your request for your help to exam the issues.
1. Issue 1: Please find the attached of screen capture when I run: "tensorhive init", then "tensorhive test" and "tensorhive". So far, I did not encounter any issue during this time. Then from picture4 to picture7 when I tried to log in into the host where tensorhive installed at IP: 10.0.2.15, it shown error as on picture4.
![Picture6](https://user-images.githubusercontent.com/78297811/107225359-a780d480-6a53-11eb-8752-b389044f7351.png)
![Picture7](https://user-images.githubusercontent.com/78297811/107225363-a8196b00-6a53-11eb-946b-6a8c083c2968.png)
![Picture1](https://user-images.githubusercontent.com/78297811/107225344-a3ed4d80-6a53-11eb-9c67-b4b400eef5cf.png)
![Picture2](https://user-images.githubusercontent.com/78297811/107225351-a5b71100-6a53-11eb-8d32-179b4244ccad.png)
![Picture3](https://user-images.githubusercontent.com/78297811/107225353-a64fa780-6a53-11eb-919d-683d10c92d06.png)
![Picture4](https://user-images.githubusercontent.com/78297811/107225355-a6e83e00-6a53-11eb-98a9-81a2e25600e6.png)
![Picture5](https://user-images.githubusercontent.com/78297811/107225357-a6e83e00-6a53-11eb-8f68-6a303cf2938a.png)

2. Issue 2: " they need an OS account on the first server that is monitored by TH". My current environment where TH is installed in virtualbox Ubuntu 18.04 LTS to monitor the GPU server ( server 1) with NVIDIA with ndvida-smi supported. In this case, may I know the user need an OS account on the first server which is this server 1? May I know how I can create a OS account in this 1st server?
I have copied the key and paste it into ~/.ssh/authorized_keys of this server1.

Thank you very much.
Yours Sincerely,
William Le

**Comment by roscisz** [comment]
Thank you for your input!

Looks like it has been a single issue after all.

This seems to be related to [a bug in pyjwt](https://github.com/jpadilla/pyjwt/issues/529). Could you kindly:
- report the pyjwt version in your environment (`pip show pyjwt | grep Version`)
- try fixing the issue by `pip install pyjwt=1.7.1` in the Python environment, where TH is executed

Regarding my vague "first monitored server" statement, what I mean is the first host entry in the `~/.config/TensorHive/hosts_config.ini` file. In your case it seems to be the GPU server (server 1).

Just to clarify, the user created by `tensorhive init` does not need neither to register, nor configure the `authorized_keys`. They might use the `authorized_keys` entry to fully utilize the `Task Execution` module, but it is not required in order to log in. The `register` button is for those users who already have accounts on the monitored host, but have no TH account yet. They can authorize themselves using the `authorized_keys` entry and set their own password, so that admin doesn't have to do this.

Hope it helps, looking forward to your results.

**Comment by William-Le88** [comment]
Dear Roscisz,

Thank you very much for kind support.
![01_check pyjwt version](https://user-images.githubusercontent.com/78297811/107627938-e9e82280-6c9a-11eb-88ef-b09bc139205d.png)
![02 1_check pyjwt=1 7 1 version](https://user-images.githubusercontent.com/78297811/107627942-eb194f80-6c9a-11eb-994d-321992c07199.png)
![02_install pyjwt=1 7 1 version](https://user-images.githubusercontent.com/78297811/107627944-ebb1e600-6c9a-11eb-982e-d1ed50d579c0.png)
![successfully login to Tensorhive web Apps](https://user-images.githubusercontent.com/78297811/107627945-ebb1e600-6c9a-11eb-8b90-705bf989fbb7.png)

I have checked the pyjwt version as well, and it was 2.0.1 version as the picture "01_check pyjwt version".
After this, I tried to follow your suggestion to install pyjwt==1.7.1 and it was successfully installed the version 1.7.1 as picture "02.1_check pyjwt==1.7.1".

I have been able to login into Tensorhive web page now. Thank you so much.

The next step we would like to do is to develop the Web Apps with updating the UI/UX for the GPU management tool using the API sets provided from Tensorhive, please allow me to seek for your help if there is any possible issues we encounter.

Thank you very much again.

Best Regards,
William

**Comment by William-Le88** [comment]
Dear Roscisz,

Could I have report one more issue on the API when I tried to execute it from the url provided from tensorhive at: http://10.0.2.15/api/ui/ where the IP is my ubuntu server IP where TH installed.

When I executed the API for testing, I got the error code of 401 with a description of Error: Unauthorized.
Please find the attached pictures for your reference.

Could you help to advise how I could overcome this issue?
Thank you!
Yours Sincerely,
William Le
![12_API Test](https://user-images.githubusercontent.com/78297811/107630933-3cc3d900-6c9f-11eb-9a18-19224fbe9a90.png)
![10_API Test](https://user-images.githubusercontent.com/78297811/107630936-3df50600-6c9f-11eb-9bb2-3645519d4b7c.png)
![11_API Test](https://user-images.githubusercontent.com/78297811/107630938-3e8d9c80-6c9f-11eb-8847-ff42f3f0ca3e.png)

**Comment by roscisz** [comment]
Dear William,

Excellent, I'm glad it helped! I will keep this issue open, until we pin pyjwt to 1.7.1 in the upcoming release.

I am also glad to hear that you plan some modifications in webapp. I would suggest to review the list of [UI-related issues](https://github.com/roscisz/TensorHive/labels/UI) to see if we already consider similar developments and potentially increase their priority or formulate new issues. 

@filschod is currently working on UI improvements, mainly related to the `task execution` module, in this [branch](https://github.com/roscisz/TensorHive/tree/job_execution_ui_improvements/). It might be beneficial to synchronize the work.
Also, if this is feasible, I would be glad to invite you as a collaborator, so that the development can be shared on GitHub and discussed with the team on Slack. Reach me at pawel.rosciszewski@pg.edu.pl if you are interested.

Best,
PR

**Comment by roscisz** [comment]
@William-Le88 regarding your 401 problem, API usage requires authorization token. You need to get the token using the POST /user/login/ endpoint and use it in the Authorize Swagger section: 
![image](https://user-images.githubusercontent.com/766386/107935849-34f78380-6f82-11eb-9cc9-5ab2fd5ee920.png)
Also, for development it would be helpful to change the token timeout settings.

I would like to keep the discussions here related to one specific topic, also it would be convenient to discuss the development issues on Slack. So I encourage you to contact me in private, so we can continue the discussion and clean this discussion.

**Comment by William-Le88** [comment]
Dear Roszisz,

Good evening. Thank you so much for your kind support. My sincere apologies for the belated reply. It was Lunar New Year in Singapore last few days.
Yes, I am happy to have further discussion on the Web Apps and UI development on a related specific topic.
Please allow me to contact you through the email provided earlier.

Thank you again!

Best Regards,
William Le
